<a href="https://colab.research.google.com/github/almocontim/Python_Pandas/blob/main/Primeiro_Exemplo_em_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Meu primeiro exemplo de manipulação de dados usando Python Pandas.**

Autor: Almo Contim
Data: 6 a 10 de fevereiro de 2023

In [ ]:
#Importando biblioteca pandas no Python

Hello World!

In [2]:
import pandas as pd
combustiveis_df = pd.read_excel("/content/ca-2021-02.xlsx")
print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [6]:
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [9]:
display(combustiveis_df.head(10))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA

In [40]:
print(combustiveis_df.shape)

(168409, 16)

In [13]:
display(combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [30]:
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [14]:
revendas = combustiveis_df["Revenda"]
display(revendas)

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [18]:
produtos_df = combustiveis_df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda']]
display(produtos_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [ ]:
#Localiza uma linha (usando o índice, começa em zero)
#Quarta linha do dataset

In [19]:
display(combustiveis_df.loc[3])

Regiao - Sigla                         NE
Estado - Sigla                         AL
Municipio                       ARAPIRACA
Revenda              POSTO ARAPIRACA LTDA
CNPJ da Revenda        12.451.076/0004-65
Nome da Rua                RODOVIA AL 220
Numero Rua                            105
Complemento                         KM 68
Bairro                        CANAFISTULA
Cep                             57302-605
Produto                GASOLINA ADITIVADA
Data da Coleta        2021-11-01 00:00:00
Valor de Venda                      6.899
Valor de Compra                       NaN
Unidade de Medida              R$ / litro
Bandeira                    VIBRA ENERGIA
Name: 3, dtype: object

In [ ]:
#Terceira até a sexta linha

In [20]:
display(combustiveis_df.loc[2:5])

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
#localizar linhas que correspondam a uma condição específica

In [46]:
vendas_gasolina_df = combustiveis_df.loc[combustiveis_df['Produto'] =='GASOLINA']
display(vendas_gasolina_df)

display(vendas_gasolina_df['Valor de Venda'].max())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA
19,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,GASOLINA,2021-11-01,6.990,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168392,SE,SP,BAURU,AUTO POSTO KM BAURU LTDA,30.550.652/0001-60,RUA CAMPOS SALLES,22160,NaN,VILA FALCAO,17050-000,GASOLINA,2021-12-31,6.199,NaN,R$ / litro,RAIZEN
168394,SE,MG,ITUIUTABA,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,45.236.791/0107-40,AVENIDA GOVERNADOR JOSE DE MAGALHAES PINTO,131,NaN,MARIA VILELA,38301-078,GASOLINA,2021-12-31,6.899,NaN,R$ / litro,IPIRANGA
168399,SE,RJ,CAMPOS DOS GOYTACAZES,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,20.641.704/0001-50,AVENIDA ALBERTO TORRES,512,CONJ 512/520 ANEXO ESQUINA COM A ...,PARQUE LEOPOLDINA,28051-287,GASOLINA,2021-12-31,7.090,NaN,R$ / litro,BRANCA
168403,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,GASOLINA,2021-12-31,6.799,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

7.999

In [ ]:
#Exibir qial é o posto e município da gasolina mais cara do país?

In [8]:
display(combustiveis_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                         8.99
dtype: object

In [ ]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são so preços do ETANOL na minha cidade
#Ordenado do menor preço para o maior

In [14]:
etanol_indaiatuba_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'ETANOL') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE')]
display(etanol_indaiatuba_df.sort_values(by='Valor de Venda'))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
144994,SE,MG,BELO HORIZONTE,POSTO GALL LTDA,21.953.856/0001-51,RUA BELMIRO BRAGA,1078,NaN,CAIÇARA,30720-520,ETANOL,2021-12-22,5.098,NaN,R$ / litro,VIBRA ENERGIA
164146,SE,MG,BELO HORIZONTE,POSTO BOM BOM LTDA,19.902.337/0001-12,AVENIDA CONTORNO,2694,NaN,SANTA EFIGENIA,30110-014,ETANOL,2021-12-29,5.259,NaN,R$ / litro,IPIRANGA
164116,SE,MG,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,06.296.943/0001-90,AVENIDA JOSE CLETO,152,NaN,PALMARES,31160-470,ETANOL,2021-12-29,5.260,NaN,R$ / litro,BRANCA
125936,SE,MG,BELO HORIZONTE,POSTO ZEPPE JARDIM LTDA,07.589.892/0001-57,RUA GUARUJA,20,NaN,NOVA SUICA,30480-630,ETANOL,2021-12-15,5.265,NaN,R$ / litro,VIBRA ENERGIA
135386,SE,MG,BELO HORIZONTE,POSTO ZEPPE JARDIM LTDA,07.589.892/0001-57,RUA GUARUJA,20,NaN,NOVA SUICA,30480-630,ETANOL,2021-12-20,5.265,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50264,SE,MG,BELO HORIZONTE,POSTO CACHOEIRINHA LTDA.,04.168.447/0001-25,AVENIDA BERNARDO DE VASCONCELOS,2265,NaN,IPIRANGA,31160-440,ETANOL,2021-11-17,5.599,NaN,R$ / litro,VIBRA ENERGIA
128965,SE,MG,BELO HORIZONTE,POSTO BRUNATA LTDA,66.333.501/0001-06,RUA ANAPURUS,21,NaN,SAO GABRIEL,31980-210,ETANOL,2021-12-16,5.599,NaN,R$ / litro,IPIRANGA
31274,SE,MG,BELO HORIZONTE,POSTO MARTE LTDA,03.638.042/0001-40,RUA JACUI,1712,NaN,GRACA,31110-050,ETANOL,2021-11-10,5.599,NaN,R$ / litro,RAIZEN
31237,SE,MG,BELO HORIZONTE,POSTO PHOENIX LTDA,71.155.998/0001-41,RUA PLATINA,999,NaN,PRADO,30411-095,ETANOL,2021-11-10,5.635,NaN,R$ / litro,RAIZEN
69742,SE,MG,BELO HORIZONTE,POSTO BH LTDA,19.983.865/0001-43,AVENIDA DOS ANDRADAS,1350,NaN,CENTRO,30120-010,ETANOL,2021-11-24,5.742,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
#Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?

In [38]:
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') 
                            & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [ ]:
#Utilizando o ISIN

In [39]:
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [ ]:
#Como mostrar média de valor de vendas Por Combustível?

In [47]:
media_por_combustivel = combustiveis_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [ ]:
#Quero adicionar uma coluna de valor booleano chamda "Ativo" que, por padrão, vai ser True para TODAS as linhas

In [48]:
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [ ]:
#inserção simples de dado

In [3]:
combustiveis_df['Ativo'] = True
display(combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [ ]:
#E se eu quiser uma coluna nova chamada "Obs"
#e que preencha automaticamente "Melhor Cidade"
#quando o |Município for SAO PAULO, MG

In [11]:
combustiveis_df['Obs'] = ["MELHOR CIDADE" if municipio == 'SAO PAULO' else None for municipio in combustiveis_df['Municipio']]
display(combustiveis_df.loc[combustiveis_df['Municipio'].isin(['SAO PAULO','INDAIATUBA', 'CAMPINAS', 'SALTO']), ['Municipio', 'Obs']])

        Municipio            Obs
1601    SAO PAULO  MELHOR CIDADE
1602    SAO PAULO  MELHOR CIDADE
1603    SAO PAULO  MELHOR CIDADE
1604    SAO PAULO  MELHOR CIDADE
2607     CAMPINAS           None
...           ...            ...
165925  SAO PAULO  MELHOR CIDADE
165926  SAO PAULO  MELHOR CIDADE
166122  SAO PAULO  MELHOR CIDADE
166123  SAO PAULO  MELHOR CIDADE
166124  SAO PAULO  MELHOR CIDADE

[7742 rows x 2 columns]

In [26]:
import numpy as np
combustiveis_df['Valor de Venda - Status'] = np.where(combustiveis_df['Valor de Venda'] > 6.5, 'Caro', 'Barato')
display(combustiveis_df[['Revenda', 'Valor de Venda', 'Valor de Venda - Status']])

,Revenda,Valor de Venda,Valor de Venda - Status
0,POSTO ARAPIRACA LTDA,6.799,Caro
1,POSTO ARAPIRACA LTDA,5.299,Barato
2,POSTO ARAPIRACA LTDA,5.549,Barato
3,POSTO ARAPIRACA LTDA,6.899,Caro
4,POSTO ARAPIRACA LTDA,5.649,Barato
...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,5.859,Barato
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,6.580,Caro
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,4.740,Barato
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,5.448,Barato
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,6.580,Caro

In [ ]:
#Calcular os postos de gasolina por habitantes temos na amostragem de combustíveis nov/2021

In [35]:
num_habitantes_df = pd.read_csv("/content/ibge_num_habitantes_estimado.csv", sep=";")
num_habitantes_df.rename(columns={"Estado":"Estado - Sigla"}, inplace=True)
display(num_habitantes_df)

         Municipio Estado - Sigla  NumHabitantes2021
0   BELO HORIZONTE             MG            2530701
1         CAMPINAS             SP            1223237
2     CAMPO GRANDE             MS             916001
3         CURITIBA             PR            1963726
4          GOIANIA             GO            1555626
5       INDAIATUBA             SP             260690
6            NATAL             RN             803739
7           PALMAS             TO             313349
8        PENAPOLIS             SP              64098
9     PORTO ALEGRE             RS            1492530
10     PORTO VELHO             RO             548952
11      RIO BRANCO             AC             419452
12  RIO DE JANEIRO             RJ            6775561
13    SALTO GRANDE             SP               9396
14          SANTOS             SP             433991
15       SAO PAULO             SP           12396372
16     SAO VICENTE             SP             370839
17     SERRA NEGRA             SP              29669

In [74]:
# Faz um MERGE dos dois dataframes
colunas = ['Municipio', 'Estado - Sigla']
merge_df = combustiveis_df.merge(num_habitantes_df, how="inner", on=colunas)
display(merge_df)
print(merge_df.info())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,...,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo,Obs,Status preco,Status preco - Status,Valor de Venda - Status,NumHabitantes2021
0,CO,GO,GOIANIA,AERO SETE AUTO POSTO LTDA,37.831.484/0001-20,AVENIDA VEREADOR JOSE MONTEIRO,1854,QUADRA08 LOTE 11E,SETOR NEGRAO DE LIMA,74650-300,...,6.999,NaN,R$ / litro,RAIZEN,True,None,Caro,Caro,Caro,1555626
1,CO,GO,GOIANIA,AERO SETE AUTO POSTO LTDA,37.831.484/0001-20,AVENIDA VEREADOR JOSE MONTEIRO,1854,QUADRA08 LOTE 11E,SETOR NEGRAO DE LIMA,74650-300,...,4.990,NaN,R$ / litro,RAIZEN,True,None,Barato,Barato,Barato,1555626
2,CO,GO,GOIANIA,AERO SETE AUTO POSTO LTDA,37.831.484/0001-20,AVENIDA VEREADOR JOSE MONTEIRO,1854,QUADRA08 LOTE 11E,SETOR NEGRAO DE LIMA,74650-300,...,7.130,NaN,R$ / litro,RAIZEN,True,None,Caro,Caro,Caro,1555626
3,CO,GO,GOIANIA,POSTO DO BOI LTDA,06.880.293/0001-25,AVENIDA INDEPENDENCIA,2.908,NaN,VILA NOVA,74645-010,...,6.990,NaN,R$ / litro,BRANCA,True,None,Caro,Caro,Caro,1555626
4,CO,GO,GOIANIA,POSTO DO BOI LTDA,06.880.293/0001-25,AVENIDA INDEPENDENCIA,2.908,NaN,VILA NOVA,74645-010,...,4.990,NaN,R$ / litro,BRANCA,True,None,Barato,Barato,Barato,1555626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20629,SE,SP,INDAIATUBA,POSTO DOS ESTEVES LTDA,20.763.169/0001-00,AVENIDA ITORORO,160,NaN,CENTRO,13330-055,...,6.499,NaN,R$ / litro,IPIRANGA,True,None,Barato,Barato,Barato,260690
20630,SE,SP,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,30.253.289/0001-11,AVENIDA PRESIDENTE KENNEDY,496,NaN,CIDADE NOVA I,13334-170,...,5.499,NaN,R$ / litro,RAIZEN,True,None,Barato,Barato,Barato,260690
20631,SE,SP,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,30.253.289/0001-11,AVENIDA PRESIDENTE KENNEDY,496,NaN,CIDADE NOVA I,13334-170,...,6.699,NaN,R$ / litro,RAIZEN,True,None,Caro,Caro,Caro,260690
20632,SE,SP,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,30.253.289/0001-11,AVENIDA PRESIDENTE KENNEDY,496,NaN,CIDADE NOVA I,13334-170,...,4.899,NaN,R$ / litro,RAIZEN,True,None,Barato,Barato,Barato,260690
20633,SE,SP,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,30.253.289/0001-11,AVENIDA PRESIDENTE KENNEDY,496,NaN,CIDADE NOVA I,13334-170,...,6.299,NaN,R$ / litro,RAIZEN,True,None,Barato,Barato,Barato,260690

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20634 entries, 0 to 20633
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Regiao - Sigla           20634 non-null  object
 1   Estado - Sigla           20634 non-null  object
 2   Municipio                20634 non-null  object
 3   Revenda                  20634 non-null  object
 4   CNPJ da Revenda          20634 non-null  object
 5   Nome da Rua              20634 non-null  object
 6   Numero Rua               20634 non-null  object
 7   Complemento              3837 non-null   object
 8   Bairro                   20634 non-null  object
 9   Cep                      20634 non-null  object
 10  Produto                  20634 non-null  object
 11  Data da Coleta           20634 non-null  datetime64[ns]
 12  Valor de Venda           20634 non-null  float64
 13  Valor de Compra          0 non-null      float64
 14  Unidade de Medida        20634 non-null  object
 15  Bandeira                 20634 non-null  object
 16  Ativo                    20634 non-null  bool
 17  Obs                      5220 non-null   object
 18  Status preco             20634 non-null  object
 19  Status preco - Status    20634 non-null  object
 20  Valor de Venda - Status  20634 non-null  object
 21  NumHabitantes2021        20634 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(17)
memory usage: 3.5+ MB
None

In [75]:
#Destruir coluna completamente vazia (todas as linhas são nulas)
merge_df.dropna(axis='columns', inplace=True)
print(merge_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20634 entries, 0 to 20633
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Regiao - Sigla           20634 non-null  object
 1   Estado - Sigla           20634 non-null  object
 2   Municipio                20634 non-null  object
 3   Revenda                  20634 non-null  object
 4   CNPJ da Revenda          20634 non-null  object
 5   Nome da Rua              20634 non-null  object
 6   Numero Rua               20634 non-null  object
 7   Bairro                   20634 non-null  object
 8   Cep                      20634 non-null  object
 9   Produto                  20634 non-null  object
 10  Data da Coleta           20634 non-null  datetime64[ns]
 11  Valor de Venda           20634 non-null  float64
 12  Unidade de Medida        20634 non-null  object
 13  Bandeira                 20634 non-null  object
 14  Ativo                    20634 non-null  bool
 15  Status preco             20634 non-null  object
 16  Status preco - Status    20634 non-null  object
 17  Valor de Venda - Status  20634 non-null  object
 18  NumHabitantes2021        20634 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(15)
memory usage: 3.0+ MB
None

In [77]:
colunas=['Regiao - Sigla', 'Nome da Rua', 'Numero Rua', 
         'Bairro', 'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda',
         'Unidade de Medida', 'Bandeira', 'Ativo']
merge_df.drop(labels=colunas, axis=1, inplace=True)
print(merge_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20634 entries, 0 to 20633
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Estado - Sigla           20634 non-null  object
 1   Municipio                20634 non-null  object
 2   Revenda                  20634 non-null  object
 3   CNPJ da Revenda          20634 non-null  object
 4   Status preco             20634 non-null  object
 5   Status preco - Status    20634 non-null  object
 6   Valor de Venda - Status  20634 non-null  object
 7   NumHabitantes2021        20634 non-null  int64
dtypes: int64(1), object(7)
memory usage: 1.4+ MB
None

In [51]:
display(merge_df.head(100))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira,Ativo,Status preco,Status preco - Status,Valor de Venda - Status
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,57302-605,GASOLINA,2021-11-01,6.799,R$ / litro,VIBRA ENERGIA,True,Caro,Caro,Caro
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,57302-605,ETANOL,2021-11-01,5.299,R$ / litro,VIBRA ENERGIA,True,Barato,Barato,Barato
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,57302-605,DIESEL,2021-11-01,5.549,R$ / litro,VIBRA ENERGIA,True,Barato,Barato,Barato
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,R$ / litro,VIBRA ENERGIA,True,Caro,Caro,Caro
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,57302-605,DIESEL S10,2021-11-01,5.649,R$ / litro,VIBRA ENERGIA,True,Barato,Barato,Barato
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NE,BA,SALVADOR,J&J COMBUSTIVEIS LTDA,06.115.130/0001-56,AVENIDA ANTONIO CARLOS MAGALHAES,40265-200,DIESEL S10,2021-11-01,5.890,R$ / litro,IPIRANGA,True,Barato,Barato,Barato
96,NE,BA,SALVADOR,J&J COMBUSTIVEIS LTDA,06.115.130/0001-56,AVENIDA ANTONIO CARLOS MAGALHAES,40265-200,GNV,2021-11-01,4.290,R$ / m³,IPIRANGA,True,Barato,Barato,Barato
97,NE,BA,SALVADOR,ECOPOSTOS - COMBUSTIVEIS E SERVICOS LTDA,04.420.464/0003-70,AVENIDA PROFESSOR PINTO DE AGUIAR,41740-090,GASOLINA,2021-11-01,6.990,R$ / litro,VIBRA ENERGIA,True,Caro,Caro,Caro
98,NE,BA,SALVADOR,ECOPOSTOS - COMBUSTIVEIS E SERVICOS LTDA,04.420.464/0003-70,AVENIDA PROFESSOR PINTO DE AGUIAR,41740-090,ETANOL,2021-11-01,5.990,R$ / litro,VIBRA ENERGIA,True,Barato,Barato,Barato
99,NE,BA,SALVADOR,ECOPOSTOS - COMBUSTIVEIS E SERVICOS LTDA,04.420.464/0003-70,AVENIDA PROFESSOR PINTO DE AGUIAR,41740-090,GASOLINA ADITIVADA,2021-11-01,7.290,R$ / litro,VIBRA ENERGIA,True,Caro,Caro,Caro

In [58]:
merge_df.drop_duplicates(inplace=True)
display(merge_df.head(100))

,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Status preco,Status preco - Status,Valor de Venda - Status
0,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,Caro,Caro,Caro
1,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,Barato,Barato,Barato
5,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,Caro,Caro,Caro
6,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,Barato,Barato,Barato
10,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,Caro,Caro,Caro
...,...,...,...,...,...,...,...
186,BA,SALVADOR,POSTO NOVO BAIRRO LTDA,13.706.262/0001-18,Barato,Barato,Barato
189,BA,SALVADOR,POSTO DO CRISTO DE COMBUSTIVEIS LTDA,13.612.767/0001-13,Caro,Caro,Caro
190,BA,SALVADOR,POSTO DO CRISTO DE COMBUSTIVEIS LTDA,13.612.767/0001-13,Barato,Barato,Barato
193,BA,SALVADOR,POSTOS MATARIPE ABASTECIMENTOS E SERVICOS LTDA,13.578.265/0001-13,Caro,Caro,Caro
194,BA,SALVADOR,POSTOS MATARIPE ABASTECIMENTOS E SERVICOS LTDA,13.578.265/0001-13,Barato,Barato,Barato

In [78]:
#Agrupar e contar quantos postos tem na cidade
postos_por_municipio_df = merge_df.groupby(by=['Estado - Sigla', 'Municipio', 'NumHabitantes2021']).count()
postos_por_municipio_df.drop('CNPJ da Revenda', axis=1, inplace=True)
postos_por_municipio_df.rename(columns={"Revenda": "Número de Postos"}, inplace=True)
display(postos_por_municipio_df)

                                                 Número de Postos  \
Estado - Sigla Municipio      NumHabitantes2021
AC             RIO BRANCO     419452                         1090
GO             GOIANIA        1555626                        1667
MG             BELO HORIZONTE 2530701                         827
MS             CAMPO GRANDE   916001                         1606
PR             CURITIBA       1963726                        1291
RJ             RIO DE JANEIRO 6775561                        2445
RN             NATAL          803739                         1093
RO             PORTO VELHO    548952                          805
RS             PORTO ALEGRE   1492530                        1142
SP             CAMPINAS       1223237                        1605
               INDAIATUBA     260690                          562
               SANTOS         433991                          459
               SAO PAULO      12396372                       5220
               SAO VICENTE    370839                          453
TO             PALMAS         313349                          369

                                                 Status preco  \
Estado - Sigla Municipio      NumHabitantes2021
AC             RIO BRANCO     419452                     1090
GO             GOIANIA        1555626                    1667
MG             BELO HORIZONTE 2530701                     827
MS             CAMPO GRANDE   916001                     1606
PR             CURITIBA       1963726                    1291
RJ             RIO DE JANEIRO 6775561                    2445
RN             NATAL          803739                     1093
RO             PORTO VELHO    548952                      805
RS             PORTO ALEGRE   1492530                    1142
SP             CAMPINAS       1223237                    1605
               INDAIATUBA     260690                      562
               SANTOS         433991                      459
               SAO PAULO      12396372                   5220
               SAO VICENTE    370839                      453
TO             PALMAS         313349                      369

                                                 Status preco - Status  \
Estado - Sigla Municipio      NumHabitantes2021
AC             RIO BRANCO     419452                              1090
GO             GOIANIA        1555626                             1667
MG             BELO HORIZONTE 2530701                              827
MS             CAMPO GRANDE   916001                              1606
PR             CURITIBA       1963726                             1291
RJ             RIO DE JANEIRO 6775561                             2445
RN             NATAL          803739                              1093
RO             PORTO VELHO    548952                               805
RS             PORTO ALEGRE   1492530                             1142
SP             CAMPINAS       1223237                             1605
               INDAIATUBA     260690                               562
               SANTOS         433991                               459
               SAO PAULO      12396372                            5220
               SAO VICENTE    370839                               453
TO             PALMAS         313349                               369

                                                 Valor de Venda - Status
Estado - Sigla Municipio      NumHabitantes2021
AC             RIO BRANCO     419452                                1090
GO             GOIANIA        1555626                               1667
MG             BELO HORIZONTE 2530701                                827
MS             CAMPO GRANDE   916001                                1606
PR             CURITIBA       1963726                               1291
RJ             RIO DE JANEIRO 6775561                               2445
RN             NATAL          803739                                1093
RO             PORTO VELHO    548952                                 805
RS             PORTO ALEGRE   1492530                               1142
SP             CAMPINAS       1223237                               1605
               INDAIATUBA     260690                                 562
               SANTOS         433991                                 459
               SAO PAULO      12396372                              5220
               SAO VICENTE    370839                                 453
TO             PALMAS         313349                                 369

In [52]:
#Exportar para Excel o DataFrame com etanol em Indaiatuba...
etanol_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')

In [ ]:
#Múltiplas condições

In [27]:
vendas_gasolina_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'GASOLINA') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE')]
display(vendas_gasolina_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,...,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo,Obs,Status preco,Status preco - Status,Valor de Venda - Status
12198,SE,MG,BELO HORIZONTE,POSTO TUNEL LTDA,08.160.834/0001-76,AVENIDA CRISTIANO MACHADO,71,NaN,FLORESTA,31110-230,...,2021-11-03,6.785,NaN,R$ / litro,IPIRANGA,True,None,Caro,Caro,Caro
12201,SE,MG,BELO HORIZONTE,POSTO CN LTDA,07.362.678/0001-63,AVENIDA CRISTIANO MACHADO,1383,NaN,DA GRACA,31140-660,...,2021-11-03,6.774,NaN,R$ / litro,RAIZEN,True,None,Caro,Caro,Caro
12206,SE,MG,BELO HORIZONTE,POSTO MINAS SHOPPING LTDA,06.980.628/0001-87,AVENIDA CRISTIANO MACHADO,3400,NaN,UNIAO,31160-342,...,2021-11-03,6.775,NaN,R$ / litro,VIBRA ENERGIA,True,None,Caro,Caro,Caro
12209,SE,MG,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,06.296.943/0001-90,AVENIDA JOSE CLETO,152,NaN,PALMARES,31160-470,...,2021-11-03,6.790,NaN,R$ / litro,BRANCA,True,None,Caro,Caro,Caro
12212,SE,MG,BELO HORIZONTE,POSTO DO PAPAI LTDA,17.418.377/0001-68,RUA POUSO ALEGRE,1500,NaN,FLORESTA,31015-030,...,2021-11-03,6.845,NaN,R$ / litro,IPIRANGA,True,None,Caro,Caro,Caro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165348,SE,MG,BELO HORIZONTE,POSTO R.E.M. LTDA,41.705.211/0003-79,AVENIDA DO CONTORNO,10040,NaN,BARRO PRETO,30110-072,...,2021-12-29,6.759,NaN,R$ / litro,VIBRA ENERGIA,True,None,Caro,Caro,Caro
166200,SE,MG,BELO HORIZONTE,POSTO PARQUE LTDA,29.333.352/0001-40,AVENIDA BERNARDO DE VASCONCELOS,2001,NaN,SANTA CRUZ,31150-000,...,2021-12-29,6.749,NaN,R$ / litro,VIBRA ENERGIA,True,None,Caro,Caro,Caro
166318,SE,MG,BELO HORIZONTE,POSTO ZEPPELIN LTDA,27.476.355/0001-08,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK,3050,NaN,PADRE EUSTAQUIO,30530-555,...,2021-12-29,6.755,NaN,R$ / litro,IPIRANGA,True,None,Caro,Caro,Caro
166508,SE,MG,BELO HORIZONTE,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,36.023.813/0001-44,RUA PLATINA,789,TERREO TERREO A,PRADO,30411-095,...,2021-12-29,6.755,NaN,R$ / litro,IPIRANGA,True,None,Caro,Caro,Caro
166545,SE,MG,BELO HORIZONTE,POSTO FLORESTA LTDA.,35.721.974/0001-49,RUA POUSO ALEGRE,1075,NaN,FLORESTA,31015-215,...,2021-12-29,6.744,NaN,R$ / litro,RAIZEN,True,None,Caro,Caro,Caro

In [ ]:
#Condicional especificando Colunas

In [23]:
vendas_gasolina_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'GASOLINA') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE'), 
                                         ['Municipio', 'Revenda', 'Data da Coleta', 'Produto', 'Valor de Venda']]
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12198,BELO HORIZONTE,POSTO TUNEL LTDA,2021-11-03,GASOLINA,6.785
12201,BELO HORIZONTE,POSTO CN LTDA,2021-11-03,GASOLINA,6.774
12206,BELO HORIZONTE,POSTO MINAS SHOPPING LTDA,2021-11-03,GASOLINA,6.775
12209,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,2021-11-03,GASOLINA,6.790
12212,BELO HORIZONTE,POSTO DO PAPAI LTDA,2021-11-03,GASOLINA,6.845
...,...,...,...,...,...
165348,BELO HORIZONTE,POSTO R.E.M. LTDA,2021-12-29,GASOLINA,6.759
166200,BELO HORIZONTE,POSTO PARQUE LTDA,2021-12-29,GASOLINA,6.749
166318,BELO HORIZONTE,POSTO ZEPPELIN LTDA,2021-12-29,GASOLINA,6.755
166508,BELO HORIZONTE,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,2021-12-29,GASOLINA,6.755
166545,BELO HORIZONTE,POSTO FLORESTA LTDA.,2021-12-29,GASOLINA,6.744

In [ ]:
#Informação nova partir de uma coluna que existe

In [31]:
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Valor de Venda'] * 0.10
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
#Removendo colunas - axis=1 é coluna/axis=0 é linha

In [32]:
vendas_gasolina_df = vendas_gasolina_df.drop("Imposto", axis=1)
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Deletar linhas e colunas completamente vazias

In [33]:
vendas_gasolina_df = vendas_gasolina_df.dropna(how='all')
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Deletar colunas completamente vazias

In [36]:
vendas_gasolina_df = vendas_gasolina_df.dropna(how='all', axis=1)
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Preencher automático com a média da coluna

In [42]:
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Valor de Venda'] * 0.10
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Imposto'].fillna(vendas_gasolina_df['Imposto'].mean())
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
#Grupo by

In [43]:
media_por_produto = combustiveis_df[['Produto', 'Valor de Venda']].groupby('Produto').mean()
display(media_por_produto)

                    Valor de Venda
Produto
DIESEL                    5.375682
DIESEL S10                5.454901
ETANOL                    5.456115
GASOLINA                  6.708741
GASOLINA ADITIVADA        6.860422
GNV                       4.392935

In [ ]:
#Salvando um novo excel

In [44]:
media_por_produto.to_excel("media_por_produto.xlsx")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')