<a href="https://colab.research.google.com/github/almocontim/Python_Pandas/blob/main/Primeiro_Exemplo_em_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Meu primeiro exemplo de manipulação de dados usando Python Pandas.**

Autor: Almo Contim
Data: 6 e 7 de fevereiro de 2023

In [ ]:
#Importando biblioteca pandas no Python

Hello World!

In [7]:
import pandas as pd
combustiveis_df = pd.read_excel("/content/ca-2021-02.xlsx")
print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [6]:
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [9]:
display(combustiveis_df.head(10))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA

In [40]:
print(combustiveis_df.shape)

(168409, 16)

In [13]:
display(combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [30]:
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [14]:
revendas = combustiveis_df["Revenda"]
display(revendas)

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [18]:
produtos_df = combustiveis_df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda']]
display(produtos_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [ ]:
#Localiza uma linha (usando o índice, começa em zero)
#Quarta linha do dataset

In [19]:
display(combustiveis_df.loc[3])

Regiao - Sigla                         NE
Estado - Sigla                         AL
Municipio                       ARAPIRACA
Revenda              POSTO ARAPIRACA LTDA
CNPJ da Revenda        12.451.076/0004-65
Nome da Rua                RODOVIA AL 220
Numero Rua                            105
Complemento                         KM 68
Bairro                        CANAFISTULA
Cep                             57302-605
Produto                GASOLINA ADITIVADA
Data da Coleta        2021-11-01 00:00:00
Valor de Venda                      6.899
Valor de Compra                       NaN
Unidade de Medida              R$ / litro
Bandeira                    VIBRA ENERGIA
Name: 3, dtype: object

In [ ]:
#Terceira até a sexta linha

In [20]:
display(combustiveis_df.loc[2:5])

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
#localizar linhas que correspondam a uma condição específica

In [46]:
vendas_gasolina_df = combustiveis_df.loc[combustiveis_df['Produto'] =='GASOLINA']
display(vendas_gasolina_df)

display(vendas_gasolina_df['Valor de Venda'].max())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA
19,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,GASOLINA,2021-11-01,6.990,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168392,SE,SP,BAURU,AUTO POSTO KM BAURU LTDA,30.550.652/0001-60,RUA CAMPOS SALLES,22160,NaN,VILA FALCAO,17050-000,GASOLINA,2021-12-31,6.199,NaN,R$ / litro,RAIZEN
168394,SE,MG,ITUIUTABA,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,45.236.791/0107-40,AVENIDA GOVERNADOR JOSE DE MAGALHAES PINTO,131,NaN,MARIA VILELA,38301-078,GASOLINA,2021-12-31,6.899,NaN,R$ / litro,IPIRANGA
168399,SE,RJ,CAMPOS DOS GOYTACAZES,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,20.641.704/0001-50,AVENIDA ALBERTO TORRES,512,CONJ 512/520 ANEXO ESQUINA COM A ...,PARQUE LEOPOLDINA,28051-287,GASOLINA,2021-12-31,7.090,NaN,R$ / litro,BRANCA
168403,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,GASOLINA,2021-12-31,6.799,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

7.999

In [ ]:
#Exibir qial é o posto e município da gasolina mais cara do país?

In [8]:
display(combustiveis_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                         8.99
dtype: object

In [ ]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são so preços do ETANOL na minha cidade
#Ordenado do menor preço para o maior

In [14]:
etanol_indaiatuba_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'ETANOL') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE')]
display(etanol_indaiatuba_df.sort_values(by='Valor de Venda'))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
144994,SE,MG,BELO HORIZONTE,POSTO GALL LTDA,21.953.856/0001-51,RUA BELMIRO BRAGA,1078,NaN,CAIÇARA,30720-520,ETANOL,2021-12-22,5.098,NaN,R$ / litro,VIBRA ENERGIA
164146,SE,MG,BELO HORIZONTE,POSTO BOM BOM LTDA,19.902.337/0001-12,AVENIDA CONTORNO,2694,NaN,SANTA EFIGENIA,30110-014,ETANOL,2021-12-29,5.259,NaN,R$ / litro,IPIRANGA
164116,SE,MG,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,06.296.943/0001-90,AVENIDA JOSE CLETO,152,NaN,PALMARES,31160-470,ETANOL,2021-12-29,5.260,NaN,R$ / litro,BRANCA
125936,SE,MG,BELO HORIZONTE,POSTO ZEPPE JARDIM LTDA,07.589.892/0001-57,RUA GUARUJA,20,NaN,NOVA SUICA,30480-630,ETANOL,2021-12-15,5.265,NaN,R$ / litro,VIBRA ENERGIA
135386,SE,MG,BELO HORIZONTE,POSTO ZEPPE JARDIM LTDA,07.589.892/0001-57,RUA GUARUJA,20,NaN,NOVA SUICA,30480-630,ETANOL,2021-12-20,5.265,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50264,SE,MG,BELO HORIZONTE,POSTO CACHOEIRINHA LTDA.,04.168.447/0001-25,AVENIDA BERNARDO DE VASCONCELOS,2265,NaN,IPIRANGA,31160-440,ETANOL,2021-11-17,5.599,NaN,R$ / litro,VIBRA ENERGIA
128965,SE,MG,BELO HORIZONTE,POSTO BRUNATA LTDA,66.333.501/0001-06,RUA ANAPURUS,21,NaN,SAO GABRIEL,31980-210,ETANOL,2021-12-16,5.599,NaN,R$ / litro,IPIRANGA
31274,SE,MG,BELO HORIZONTE,POSTO MARTE LTDA,03.638.042/0001-40,RUA JACUI,1712,NaN,GRACA,31110-050,ETANOL,2021-11-10,5.599,NaN,R$ / litro,RAIZEN
31237,SE,MG,BELO HORIZONTE,POSTO PHOENIX LTDA,71.155.998/0001-41,RUA PLATINA,999,NaN,PRADO,30411-095,ETANOL,2021-11-10,5.635,NaN,R$ / litro,RAIZEN
69742,SE,MG,BELO HORIZONTE,POSTO BH LTDA,19.983.865/0001-43,AVENIDA DOS ANDRADAS,1350,NaN,CENTRO,30120-010,ETANOL,2021-11-24,5.742,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
#Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?

In [38]:
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') 
                            & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [ ]:
#Utilizando o ISIN

In [39]:
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [ ]:
#Como mostrar média de valor de vendas Por Combustível?

In [47]:
media_por_combustivel = combustiveis_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [ ]:
#Quero adicionar uma coluna de valor booleano chamda "Ativo" que, por padrão, vai ser True para TODAS as linhas

In [48]:
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [ ]:
#E se eu quiser uma coluna nova chamada "Obs"
#e que preencha automaticamente "Melhor Cidade"
#quando o |Município for BELO HORIZONTE, MG

In [ ]:
#combustiveis_df['Obs'] = "MELHOR CIDADE" if combustiveis_df['MUNICIPIO'] == "BELO HORIZONTE" else ""

In [52]:
#Exportar para Excel o DataFrame com etanol em Idaiatuba...
etanol_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')

In [ ]:
#Múltiplas condições

In [11]:
vendas_gasolina_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'GASOLINA') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE')]
display(vendas_gasolina_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
12198,SE,MG,BELO HORIZONTE,POSTO TUNEL LTDA,08.160.834/0001-76,AVENIDA CRISTIANO MACHADO,71,NaN,FLORESTA,31110-230,GASOLINA,2021-11-03,6.785,NaN,R$ / litro,IPIRANGA
12201,SE,MG,BELO HORIZONTE,POSTO CN LTDA,07.362.678/0001-63,AVENIDA CRISTIANO MACHADO,1383,NaN,DA GRACA,31140-660,GASOLINA,2021-11-03,6.774,NaN,R$ / litro,RAIZEN
12206,SE,MG,BELO HORIZONTE,POSTO MINAS SHOPPING LTDA,06.980.628/0001-87,AVENIDA CRISTIANO MACHADO,3400,NaN,UNIAO,31160-342,GASOLINA,2021-11-03,6.775,NaN,R$ / litro,VIBRA ENERGIA
12209,SE,MG,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,06.296.943/0001-90,AVENIDA JOSE CLETO,152,NaN,PALMARES,31160-470,GASOLINA,2021-11-03,6.790,NaN,R$ / litro,BRANCA
12212,SE,MG,BELO HORIZONTE,POSTO DO PAPAI LTDA,17.418.377/0001-68,RUA POUSO ALEGRE,1500,NaN,FLORESTA,31015-030,GASOLINA,2021-11-03,6.845,NaN,R$ / litro,IPIRANGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165348,SE,MG,BELO HORIZONTE,POSTO R.E.M. LTDA,41.705.211/0003-79,AVENIDA DO CONTORNO,10040,NaN,BARRO PRETO,30110-072,GASOLINA,2021-12-29,6.759,NaN,R$ / litro,VIBRA ENERGIA
166200,SE,MG,BELO HORIZONTE,POSTO PARQUE LTDA,29.333.352/0001-40,AVENIDA BERNARDO DE VASCONCELOS,2001,NaN,SANTA CRUZ,31150-000,GASOLINA,2021-12-29,6.749,NaN,R$ / litro,VIBRA ENERGIA
166318,SE,MG,BELO HORIZONTE,POSTO ZEPPELIN LTDA,27.476.355/0001-08,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK,3050,NaN,PADRE EUSTAQUIO,30530-555,GASOLINA,2021-12-29,6.755,NaN,R$ / litro,IPIRANGA
166508,SE,MG,BELO HORIZONTE,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,36.023.813/0001-44,RUA PLATINA,789,TERREO TERREO A,PRADO,30411-095,GASOLINA,2021-12-29,6.755,NaN,R$ / litro,IPIRANGA
166545,SE,MG,BELO HORIZONTE,POSTO FLORESTA LTDA.,35.721.974/0001-49,RUA POUSO ALEGRE,1075,NaN,FLORESTA,31015-215,GASOLINA,2021-12-29,6.744,NaN,R$ / litro,RAIZEN

In [ ]:
#Condicional especificando Colunas

In [23]:
vendas_gasolina_df = combustiveis_df.loc[(combustiveis_df['Produto'] == 'GASOLINA') & (combustiveis_df['Municipio'] == 'BELO HORIZONTE'), 
                                         ['Municipio', 'Revenda', 'Data da Coleta', 'Produto', 'Valor de Venda']]
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12198,BELO HORIZONTE,POSTO TUNEL LTDA,2021-11-03,GASOLINA,6.785
12201,BELO HORIZONTE,POSTO CN LTDA,2021-11-03,GASOLINA,6.774
12206,BELO HORIZONTE,POSTO MINAS SHOPPING LTDA,2021-11-03,GASOLINA,6.775
12209,BELO HORIZONTE,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,2021-11-03,GASOLINA,6.790
12212,BELO HORIZONTE,POSTO DO PAPAI LTDA,2021-11-03,GASOLINA,6.845
...,...,...,...,...,...
165348,BELO HORIZONTE,POSTO R.E.M. LTDA,2021-12-29,GASOLINA,6.759
166200,BELO HORIZONTE,POSTO PARQUE LTDA,2021-12-29,GASOLINA,6.749
166318,BELO HORIZONTE,POSTO ZEPPELIN LTDA,2021-12-29,GASOLINA,6.755
166508,BELO HORIZONTE,POSTO DE COMBUSTIVEIS VILA PLATINA LTDA,2021-12-29,GASOLINA,6.755
166545,BELO HORIZONTE,POSTO FLORESTA LTDA.,2021-12-29,GASOLINA,6.744

In [ ]:
#Informação nova partir de uma coluna que existe

In [31]:
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Valor de Venda'] * 0.10
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
#Removendo colunas - axis=1 é coluna/axis=0 é linha

In [32]:
vendas_gasolina_df = vendas_gasolina_df.drop("Imposto", axis=1)
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Deletar linhas e colunas completamente vazias

In [33]:
vendas_gasolina_df = vendas_gasolina_df.dropna(how='all')
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Deletar colunas completamente vazias

In [36]:
vendas_gasolina_df = vendas_gasolina_df.dropna(how='all', axis=1)
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299
...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299

In [ ]:
#Preencher automático com a média da coluna

In [42]:
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Valor de Venda'] * 0.10
vendas_gasolina_df['Imposto'] = vendas_gasolina_df['Imposto'].fillna(vendas_gasolina_df['Imposto'].mean())
display(vendas_gasolina_df)

,Municipio,Revenda,Data da Coleta,Produto,Valor de Venda,Imposto
12773,INDAIATUBA,COMERCIAL DE COMBUSTIVEIS INDAIA US LTDA,2021-11-03,GASOLINA,6.477,0.6477
12777,INDAIATUBA,HELVETIA COMERCIO DE COMBUSTIVEIS E SERVICOS LTDA,2021-11-03,GASOLINA,6.397,0.6397
12782,INDAIATUBA,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,2021-11-03,GASOLINA,6.279,0.6279
12787,INDAIATUBA,AUTO POSTO JARDIM CALIFORNIA LTDA.,2021-11-03,GASOLINA,6.099,0.6099
12789,INDAIATUBA,POSTO TREMENDAO LUBRIFICANTES E SERVIÇOS LTDA,2021-11-03,GASOLINA,6.299,0.6299
...,...,...,...,...,...,...
159498,INDAIATUBA,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,2021-12-28,GASOLINA,6.239,0.6239
160593,INDAIATUBA,AUTO POSTO NAMORADA II LTDA.,2021-12-28,GASOLINA,5.999,0.5999
160807,INDAIATUBA,POSTO RECREIO OURO LTDA,2021-12-28,GASOLINA,6.399,0.6399
160995,INDAIATUBA,POSTO DOS ESTEVES LTDA,2021-12-28,GASOLINA,6.499,0.6499
161799,INDAIATUBA,ABDELNOR VI COMERCIO DE COMBUSTIVEIS LTDA,2021-12-28,GASOLINA,6.299,0.6299

In [ ]:
#Grupo by

In [43]:
media_por_produto = combustiveis_df[['Produto', 'Valor de Venda']].groupby('Produto').mean()
display(media_por_produto)

                    Valor de Venda
Produto
DIESEL                    5.375682
DIESEL S10                5.454901
ETANOL                    5.456115
GASOLINA                  6.708741
GASOLINA ADITIVADA        6.860422
GNV                       4.392935

In [ ]:
#Salvando um novo excel

In [44]:
media_por_produto.to_excel("media_por_produto.xlsx")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')